title: TH Classic
email: torben@thclassic.dk
baseurl: ""

# Build settings
plugins:
  - jekyll-feed

host: 0.0.0.0

sass:
    sass_dir: assets/scss

defaults:
  - scope:
      path: ""
      type: "cars"
    values:
      layout: view-car

_options:
  image_path:
    width: 1280
    height: 720
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: true

collections:
  cars:
    output: true
    permalink: /:collection/:name
    

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
