title: TH Classic
email: torben@thclassic.dk
baseurl: ""

# Build settings
plugins:
  - jekyll-feed

host: 0.0.0.0

sass:
    sass_dir: assets/scss

_options:
  image_path:
    width: 90
    height: 120
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: true
  content:
    width: 90
    height: 120
    resize_style: "cover"
    mime_type: "image/png"


defaults:
  - scope:
      path: ""
      type: "cars"
    values:
      layout: view-car

# _options:
#   image_path:
#     width: 1280
#     height: 548
#     resize_style: "contain"
#     mime_type: "image/jpeg"
#     expandable: true


collections:
  cars:
    output: true
    permalink: /biler/:name
    _image_key: images
    _images_size: contain


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
